### ISSUE TITLE
Test stop on step amOnPage

### ISSUE THREAD

**Issue by zahidmuhammadzaki** [luka-zitnik/CodeIgniterModule#3]
My functional.suite.yml

```
class_name: FunctionalTester
modules:
    enabled:
      - REST:
          depends: CodeIgniter
      - CodeIgniter:
          index: index.php
      - \Helper\Functional
```

Here is my code

```
public function register_with_empty_fields_show_alert_error(FunctionalTester $I)
    {
      $I->wantTo('Register new account with empty fields.');
      $I->amOnPage('auth/registers');
      $I->click('#btn-registers');
      $I->see('Register Your Account');
      $I->see('The Name field is required');
      $I->see('The Email field is required');
      $I->see('The Password field is required');
      $I->see('The Password Confirmation field is required');
    }
```

And here is the response, it stops there.
![capture](https://cloud.githubusercontent.com/assets/8657754/19382611/28c85b68-922b-11e6-925d-e1fe473c3cd4.JPG)
